services:
  prometheus:
    image: prom/prometheus
    ports: 
      - "9091:9090"
    privileged: true 
    extra_hosts:
            - "host.docker.internal:host-gateway"
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml" 
  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"
    environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=grafana


